#!/usr/bin/bash
# 02/09/2023 - tolerance thresholds not working under LE, false positives
# 05/19/2023 - Added ping_host and url_check

output=/tmp/health.out

# Functions
function critical () {
printf "\033[0;101m $1 \033[0m "
}
function normal () {
printf "\033[0;42m $* \033[0m "
}
function inform () {
printf "\033[0;44m $1 \033[0m "
}

function ping_host () {
    ping -c 1 $1 >/dev/null 2>&1
    trimmed_hostname=$(echo "$1" | sed 's/news\.//')
    if [ $? -eq 0 ]; then
        normal $trimmed_hostname
    else
        critical $trimmed_hostname
    fi
}

function url_check () {
    trimmed_url=$(echo "$1" | cut -d'/' -f1-1)
    if curl --output /dev/null --silent --head --fail "https://${1}"; then
        normal $trimmed_url
    else
        critical $trimmed_url
    fi
}

function cpu_load {
    load=$(uptime | awk '{print $NF}' | cut -f1 -d '.' |tr -d ' ')
    if [[ "$load" -gt "2" ]]; then
        critical cpu_load
        top -b -n 1 | head -10 >> $output 2>&1
    else
        normal cpu_load
    fi
}

function free_mem {
    mem=$(free -m | grep Mem | awk '{print $4}')
    tolerance=80
    if [[ "$mem" -lt "$tolerance" ]]; then
        critical free_mem
        free -mh >> $output 2>&1
    else
        normal free_mem
    fi
}

function diskusage () {
    diskusage=$(df /storage | grep -v Filesystem | awk '{print $5}' | cut -f1 -d '%')
    tolerance=65
    if [[ "$diskusage" == "$tolerance" ]] ;then
        critical $1
        df -h $1 >> $output 2>&1
    else
        normal $1 ${diskusage}
    fi
}

function dns {
    dns=$(nslookup 1.1.1.1 | grep one.one.one.one 2>/dev/null)
    if [[ "$dns" == "" ]] ;then critical dns ;else normal dns; fi
}

function gateway {
    gateway=$(route -n | grep 'UG[ \t]' | awk '{print $2}' 2>/dev/null)
    if [[ "$gateway" == "" ]] ;then critical gateway; else normal ${gateway}; fi
}

function wan {
    ipaddr=$(curl -s http://whatismijnip.nl |cut -d " " -f 5 2>/dev/null)
    if [[ "$ipaddr" == "" ]] ;then
        critical internet
        exit 1
    else
        normal ${ipaddr}
    fi
}

# Execute Funtions from menu
[ -f $output ] && rm $output
printf "Health: "
cpu_load
free_mem
diskusage /storage
gateway
wan
dns
url_check dognzb.cr/login
ping_host news.newshosting.com
ping_host news.newsdemon.com
printf "\n"
[ -f $output ] && cat $output
