#!/usr/bin/bash
YELLOW='\033[0;33m'
WHITE='\033[0;37m'
NC='\033[0m' # No Color

function header () {
  line="++++++++++++++++++++++++++++++++++++++++++++++++++"
  printf "\n${YELLOW}${line}\n${WHITE}${*}${YELLOW}\n${line}${NC}\n"
}

function docker_state {
  header "docker container ps"
  docker container ps
}

function docker_pull {
  header "docker-compose pull"                                                
  docker-compose pull                                                         
  header "docker-compose up -d"                              
  docker-compose up -d 
}

function docker_clean {
  header "docker-compose up -d --remove-orphans"                              
  docker-compose up -d --remove-orphans                                       
  header "docker image prune"                                                 
  docker image prune                                                    
}                                                    

while :; do
  case $1 in
    -h|--help)
      echo "$0 [OPTIONS]
      Options:
      -c --clean      removes old images not used 
      -h --help       this help text"
      exit
      ;;
    -c|--clean)
      docker_state
      docker_clean
      docker_state
      echo "Use the --clean option to remove orphans and older images"
      exit
      ;;
    *)
      docker_state
      docker_pull
      docker_state
      header "Complete!"
      date > /storage/.lastupdate
      exit
      ;;
  esac
done

